ignored:
- arn:aws:ecs:us-east-1:123456789012:cluster/production-unused
- arn:aws:eks:us-east-1:123456789012:cluster/legacy-dev-cluster
- arn:aws:eks:us-east-1:123456789012:nodegroup/production-cluster/failed-scaling-group
- arn:aws:s3:::multipart/mock-bucket-iceberg/upload-1
- arn:aws:ec2:us-east-1:123456789012:natgateway/nat-0mock12345
- arn:aws:ec2:us-east-1:123456789012:snapshot/snap-0mockChild
- arn:aws:ec2:us-east-1:123456789012:volume/vol-0mock1234567890
- arn:aws:rds:us-east-1:123456789012:db:legacy-postgres
