package report

import (
	"encoding/json"
	"fmt"
	"os"
    "time"

	"github.com/DrSkyle/cloudslash/internal/graph"
)

// GenerateDashboard creates a high-fidelity HTML report.
func GenerateDashboard(g *graph.Graph, path string) error {
	items := extractItems(g) // Reuse logic from export.go
    
    // Calculate Stats
    totalCost := 0.0
    riskCount := 0
    for _, item := range items {
        totalCost += item.MonthlyCost
        if item.RiskScore > 50 {
            riskCount++
        }
    }

	jsonData, err := json.Marshal(items)
	if err != nil {
		return err
	}

    // THE TEMPLATE (Embedded for Single-Binary Portability)
	html := fmt.Sprintf(`<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CloudSlash // Forensic Audit</title>
    <style>
        :root {
            --bg: #0A0A0A;
            --surface: rgba(255, 255, 255, 0.03);
            --border: rgba(255, 255, 255, 0.1);
            --primary: #00FF99;
            --danger: #FF3366;
            --text: #F8FAFC;
            --text-dim: #94A3B8;
        }
        body {
            background: var(--bg);
            color: var(--text);
            font-family: 'SF Mono', 'Menlo', monospace; /* Hacker aesthetic */
            margin: 0;
            padding: 40px;
        }
        .header {
            display: flex;
            justify-content: space-between;
            align-items: center;
            margin-bottom: 40px;
            border-bottom: 1px solid var(--border);
            padding-bottom: 20px;
        }
        .logo { font-size: 1.5rem; font-weight: bold; letter-spacing: -1px; }
        .logo span { color: var(--primary); }
        .meta { color: var(--text-dim); font-size: 0.9rem; }

        .kpi-grid {
            display: grid;
            grid-template-columns: repeat(3, 1fr);
            gap: 20px;
            margin-bottom: 40px;
        }
        .card {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 12px;
            padding: 24px;
            backdrop-filter: blur(10px);
        }
        .card h3 { margin: 0 0 10px 0; font-size: 0.8rem; color: var(--text-dim); text-transform: uppercase; letter-spacing: 1px; }
        .card .value { font-size: 2.5rem; font-weight: bold; }
        .card .value.cost { color: var(--danger); }
        .card .value.safe { color: var(--primary); }

        .table-container {
            background: var(--surface);
            border: 1px solid var(--border);
            border-radius: 12px;
            overflow: hidden;
        }
        table { width: 100%; border-collapse: collapse; }
        th, td { padding: 16px 24px; text-align: left; border-bottom: 1px solid var(--border); }
        th { background: rgba(0,0,0,0.3); color: var(--text-dim); font-size: 0.8rem; text-transform: uppercase; }
        tr:last-child td { border-bottom: none; }
        tr:hover { background: rgba(255,255,255,0.02); }

        .badge {
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 0.75rem;
            font-weight: bold;
        }
        .badge.JUNK { background: rgba(255, 51, 102, 0.1); color: var(--danger); border: 1px solid rgba(255, 51, 102, 0.3); }
        .badge.REVIEW { background: rgba(255, 170, 0, 0.1); color: #FFAA00; border: 1px solid rgba(255, 170, 0, 0.3); }
        
        .evidence { font-size: 0.85rem; color: var(--text-dim); }
        
        footer { margin-top: 60px; color: var(--text-dim); font-size: 0.8rem; text-align: center; }
    </style>
</head>
<body>

    <div class="header">
        <div class="logo">CLOUD<span>SLASH</span>_AUDIT</div>
        <div class="meta">Generated: %s</div>
    </div>

    <div class="kpi-grid">
        <div class="card">
            <h3>Monthly Waste</h3>
            <div class="value cost">$%.2f</div>
        </div>
        <div class="card">
            <h3>Zombie Resources</h3>
            <div class="value">%d</div>
        </div>
        <div class="card">
            <h3>Compliance Score</h3>
            <div class="value safe">FAILED</div>
        </div>
    </div>

    <div class="table-container">
        <table>
            <thead>
                <tr>
                    <th>Type</th>
                    <th>Resource ID</th>
                    <th>Region</th>
                    <th>Monthly Cost</th>
                    <th>Action</th>
                    <th>Evidence</th>
                </tr>
            </thead>
            <tbody id="table-body">
                <!-- JS Injection -->
            </tbody>
        </table>
    </div>

    <footer>
        Generated by CloudSlash v1.3.3 (AGPLv3) | Local-First Forensic Engine
    </footer>

    <script>
        // DATA INJECTION
        window.REPORT_DATA = %s;

        const tbody = document.getElementById('table-body');
        const currency = new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD' });

        window.REPORT_DATA.forEach(item => {
            const tr = document.createElement('tr');
            
            const badgeClass = item.risk_score > 50 ? 'JUNK' : 'REVIEW';
            const costClass = item.monthly_cost > 0 ? 'color: #FF3366;' : 'color: #94A3B8;';

            tr.innerHTML = ` + "`" + `
                <td><span style="opacity:0.7">` + "`" + ` + item.type + ` + "`" + `</span></td>
                <td style="font-weight:bold; color: #fff;">` + "`" + ` + item.resource_id + ` + "`" + `</td>
                <td>` + "`" + ` + item.region + ` + "`" + `</td>
                <td style="` + "`" + ` + costClass + ` + "`" + `">` + "`" + ` + currency.format(item.monthly_cost) + ` + "`" + `</td>
                <td><span class="badge ` + "`" + ` + badgeClass + ` + "`" + `">` + "`" + ` + item.action + ` + "`" + `</span></td>
                <td class="evidence">` + "`" + ` + item.forensic_evidence + ` + "`" + `</td>
            ` + "`" + `;
            tbody.appendChild(tr);
        });
    </script>
</body>
</html>`, time.Now().Format("2006-01-02 15:04:05"), totalCost, len(items), string(jsonData))

	return os.WriteFile(path, []byte(html), 0644)
}
