package report

import (
	"fmt"
	"os"
	"time"

	"github.com/DrSkyle/cloudslash/internal/graph"
	"github.com/DrSkyle/cloudslash/internal/version"
)

// GenerateExecutiveSummary creates an audit report in Markdown.
func GenerateExecutiveSummary(g *graph.Graph, path string, scanID string, accountID string) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()

	g.Mu.RLock()
	defer g.Mu.RUnlock()

	totalWasteCost := 0.0
	totalWasteCount := 0
	computeWaste := 0.0
	storageWaste := 0.0

	// Aggregate Data
	for _, node := range g.Nodes {
		if node.IsWaste {
			totalWasteCount++
			totalWasteCost += node.Cost

			if isCompute(node.Type) {
				computeWaste += node.Cost
			}
			if isStorage(node.Type) {
				storageWaste += node.Cost
			}
		}
	}

	projectedSavings := totalWasteCost * 12

	// Template
	fmt.Fprintf(f, "# CloudSlash Audit Report\n")
	fmt.Fprintf(f, "**Date:** %s\n", time.Now().Format("2006-01-02"))
	if accountID != "" {
		fmt.Fprintf(f, "**Account:** %s\n", accountID)
	} else {
		fmt.Fprintf(f, "**Account:** Unknown (Mock/Local)\n")
	}
	fmt.Fprintf(f, "**Scan ID:** %s\n\n", scanID)

	fmt.Fprintf(f, "## Executive Summary\n")
	fmt.Fprintf(f, "CloudSlash identified **%d unused resources** with a total projected annual waste of **$%.2f**.\n\n", totalWasteCount, projectedSavings)

	fmt.Fprintf(f, "### Top Waste Categories\n")
	fmt.Fprintf(f, "1. **Compute (NAT/EIP/EC2):** $%.2f/yr\n", computeWaste*12)
	fmt.Fprintf(f, "   - *Impact:* Paying for idle CPU and allocated but unused IP addresses.\n")
	fmt.Fprintf(f, "2. **Storage (EBS/S3):** $%.2f/yr\n", storageWaste*12)
	fmt.Fprintf(f, "   - *Impact:* Paying for detached volumes and old snapshots.\n\n")

	fmt.Fprintf(f, "### Recommended Action Plan\n")
	fmt.Fprintf(f, "1. **Immediate:** Run `fix_terraform.sh` to remove unused resources from state.\n")
	fmt.Fprintf(f, "2. **Cleanup:** Execute `cloudslash delete-script` to remove confirmed waste.\n")
	fmt.Fprintf(f, "3. **Safety:** Update Route53 records for any flagged Elastic IPs.\n\n")

	fmt.Fprintf(f, "---\n")
	fmt.Fprintf(f, "*Generated by CloudSlash %s*\n", version.Current)

	return nil
}

// Summary holds high-level scan statistics for reporting.
type Summary struct {
	Region       string
	TotalScanned int
	TotalWaste   int
	TotalSavings float64
}

func isCompute(t string) bool {
	return t == "AWS::EC2::Instance" || t == "AWS::EC2::NatGateway" || t == "AWS::EC2::EIP" || t == "AWS::Lambda::Function"
}

func isStorage(t string) bool {
	return t == "AWS::EC2::Volume" || t == "AWS::S3::Bucket" || t == "AWS::EC2::Snapshot"
}
